### ISSUE TITLE
Error while setting up greenchoice platform for sensor

### ISSUE THREAD

**Issue by victorclaessen** [jessevl/homeassistant-greenchoice#27]
Hi,

I have obtained the contract id, and put it together with username/password in secrets.yaml. I'm getting the following error in the log file while trying to setup this component. 

```
2021-04-11 14:23:48 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up greenchoice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 57, in setup_platform
    greenchoice_api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 278, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 203, in update
    currentEnergy = [x for x in json_result if x['MeterstandenOutput'][0]['Product'] == 1]
  File "/config/custom_components/greenchoice/sensor.py", line 203, in <listcomp>
    currentEnergy = [x for x in json_result if x['MeterstandenOutput'][0]['Product'] == 1]
TypeError: string indices must be integers
```

`sensors/greenchoice.yaml`
```
- platform: greenchoice
  name: meterstanden
  password: !secret greenchoicepass
  username: !secret greenchoiceuser
  overeenkomst_id: !secret greenchoicecontract
```

Any idea what I am doing wrong?

Thanks,

Vic

**Comment by victorclaessen** [comment]
This error went away (probably after upgrading Home Assistant Core).
