### ISSUE TITLE
Error while setting up greenchoice platform on HA release 2021.11

### ISSUE THREAD

**Issue by groenmarsmannetje** [jessevl/homeassistant-greenchoice#31]
When I start Home Assistant the following is shown in log and the custom integration is not loaded.

```
Error while setting up greenchoice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 57, in setup_platform
    greenchoice_api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 190, in update
    response.request("POST", "/token", body = self._tokenquery, headers = self._tokenheaders)
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)
```

**Comment by maikeru010** [comment]
I notice the same. When I run the POST command again I get the following error:

Error: Client network socket disconnected before secure TLS connection was established

It looks like Greenchoice has changed something, or the custom component for HACS needs an update (non is available at the moment)

**Comment by ronald-den-otter** [comment]
same problem. Would we nice if this gets resolved. Plugin totally not functional now

**Comment by PSinke** [comment]
Also getting the 'Client network socket disconnected before secure TLS connection was established' error. Has Greenchoice removed this endpoint? Maybe the mobile app changed?

**Comment by jessevl** [comment]
It seems like something has changed at the Greenchoice API end and unfortunately this API is not documented. In fact, I'm fairly certain that we've been using the API for a very old version of their app, which they probably deprecated. 

Intercepting (encrypted) traffic of a mobile app to figure out the API is very cumbersome, but I see their (new) website now also uses a proper API (https://mijn.greenchoice.nl/microbus/*) to load the data and figuring it out should be much more straightforward. 

I have very little time for this, but if somebody else does, that's where I would start.

**Comment by IeuanK** [comment]
It does indeed seem like that is their new API, the website also uses this.
Most data requests go through https://mijn.greenchoice.nl/microbus/request, with the 'name' parameter in the payload providing the actual requested endpoint. It's a pretty non-standard API built in ASP.NET, have not yet discovered how it gets and/or sends an auth token.

Sample payload for fetching data:
![image](https://user-images.githubusercontent.com/1075598/146738604-414fa801-39b8-48b5-a664-d0a2a8782b08.png)

The response is reasonable JSON:
![image](https://user-images.githubusercontent.com/1075598/146738679-32d1801b-7d70-4462-81d6-7cfec659d861.png)

**Comment by DismissedGuy** [comment]
I have hacked together a little python script that is able to perform the login sequence and get the necessary cookies. Currently it just displays the contracts associated with your account, but it is able to call any arbitrary microbus endpoint and retrieve the data.

I have zero experience with home assistant integration development, but this should be a good starting point.

https://github.com/DismissedGuy/homeassistant-greenchoice/blob/master/get-overeenkomst.py

**Comment by maikeru010** [comment]
Hi @DismissedGuy when I try to run your python script I get exceptions after I entered my username and password. Unfortunately no contract is returned, any ideas what I am doing wrong. Tried running the script from Windows and an online compiler, maybe things go wrong there?

**Comment by DismissedGuy** [comment]
> Hi @DismissedGuy when I try to run your python script I get exceptions after I entered my username and password. Unfortunately no contract is returned, any ideas what I am doing wrong. Tried running the script from Windows and an online compiler, maybe things go wrong there?

The script was developed on a Linux machine, but I can't really think of something that would be platform dependent. What exception are you running into?

In the meanwhile, I have modified the sensor to return data from the new API, so you can try it in your home assistant instance. It's a drop-in replacement as far as the config goes, but do note that I've changed the entity IDs since I don't know what data this integration returned exactly.

**Comment by maikeru010** [comment]
Thank you very much for the quick response!

Maybe I'm doing something completely wrong, but when I run this in Windows CMD it states that there is no module names bs4.

Should I place the python scripts provided by you within the Greenchoice folder in Home Assistant and run the scripts from Home Assistant? Where should I enter username en Password then?

Previously, with the old API, I had to get my Contrct number using POSTMAN and use that number within de Home Assistant configuration of Greenchoice. 

At the moment I'm a little lost where to use your scripts :-)

**Comment by DismissedGuy** [comment]
> Thank you very much for the quick response!
> 
> Maybe I'm doing something completely wrong, but when I run this in Windows CMD it states that there is no module names bs4.
> 
> Should I place the python scripts provided by you within the Greenchoice folder in Home Assistant and run the scripts from Home Assistant? Where should I enter username en Password then?
> 
> Previously, with the old API, I had to get my Contrct number using POSTMAN and use that number within de Home Assistant configuration of Greenchoice. 
> 
> At the moment I'm a little lost where to use your scripts :-)

The script has two dependencies (`requests` and `beautifulsoup4`), that you will need to install. There is a requirements.txt in the repository I linked above (https://github.com/DismissedGuy/homeassistant-greenchoice), you can install the necessary dependencies by doing `pip install -U -r requirements.txt` or the Windows equivalent.

The script I was talking about replaces the need to use postman; it will take your username and password, log in using your credentials and then return a list of overeenkomsten.

If you want to use it in Home Assistant, you should delete the current Greenchoice integration using HACS or by removing the folder in `<homeassistant_config>/custom_components/` (from the top of my head), depending on how you previously installed this integration. You should then copy the greenchoice folder in my repository to the `custom_components` folder mentioned before.

What I meant by drop-in replacement is that the configuration to set up this integration, works for mine as well. The only difference is that the entity IDs are different, but you can check to see if it's working by going to the developer options in home assistant and searching for "energy_consumption" or "energy_return." Tip: configure the logger in home assistant to set the log level for `custom_components.greenchoice` to "DEBUG" so it shows more information.

**Comment by muchall** [comment]
Any update on this?

**Comment by maikeru010** [comment]
Thanks again @DismissedGuy for the explanation. I'm on the right track. I'm using a virtualenvironment on my Windows device.

After I installed the requirements (Beautifulsoup4 and requests) the script got a lot further, but at the end there was this error:

_________________________________________________________________________________________________

Traceback (most recent call last):
  File "c:\Users\Maikeru\get-overeenkomst.py", line 71, in <module>
    main()
  File "c:\Users\Maikeru\get-overeenkomst.py", line 64, in main
    overeenkomsten_json = init_data['klantgegevens'][0]['adressen'][0]['contracten']
IndexError: list index out of range
_________________________________________________________________________________________________

**Comment by DismissedGuy** [comment]
> Thanks again @DismissedGuy for the explanation. I'm on the right track. I'm using a virtualenvironment on my Windows device.
> 
> After I installed the requirements (Beautifulsoup4 and requests) the script got a lot further, but at the end there was this error:
> 
> _________________________________________________________________________________________________
> 
> Traceback (most recent call last):
>   File "c:\Users\Maikeru\get-overeenkomst.py", line 71, in <module>
>     main()
>   File "c:\Users\Maikeru\get-overeenkomst.py", line 64, in main
>     overeenkomsten_json = init_data['klantgegevens'][0]['adressen'][0]['contracten']
> IndexError: list index out of range
> _________________________________________________________________________________________________

That's interesting... Could you maybe add `print(init_data)` above that line, try again and then send me a copy of the json it prints out? Note that it can contain sensitive information about yourself or your contract(s), so you might want to censor that out. If you'd rather share it in private, you can also email it to me at `dismissed.is.a.guy [at] gmail.com`.

This is a typical "it works for me" issue, so if I can see what the data for other people looks like, that might help with developing the new integration.

**Comment by maikeru010** [comment]
Hi, I will try. Do I have to put the extra code on top of the script or above line 64 and above line 71? Or only above line 64?

**Comment by DismissedGuy** [comment]
Only above 64 (so after the `init_data = ...`)

**Comment by maikeru010** [comment]
@DismissedGuy Hi, I've sent you an e-mail. Thanks in advance!

**Comment by tivoo** [comment]
Thanks @DismissedGuy your script works perfectly on my end. The sensor meterstanden is visible in my setup, now just waiting to see some data coming in. Cheers!

**Comment by tivoo** [comment]
Unfortunately spoke to soon. Got everything set up ok, but no data is coming in:

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: January 18, 2022, 11:38:32 (5 occurrences)
Last logged: January 18, 2022, 11:38:33

Entity sensor.meterstanden (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.energy_consumption_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.energy_consumption_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.energy_return_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.energy_return_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by DismissedGuy** [comment]
@tivoo That's quite strange; I've been successfully using the integration for almost 2 weeks now with little to no issues on my end. I just pushed some changes that should handle that error while showing what the API actually returned, could you try updating the integration and checking the logs?

If it doesn't show anything useful, you can add the following snippet to your `configuration.yaml` that should bump the log level for the integration:
```yaml
logger:
  default: error
  logs:
    custom_components.greenchoice: debug
```

**Comment by DonJuape** [comment]
@DismissedGuy Your script to get the address and contract ID works flawless! When we added some code to get energy consumption data, we get a <Response [500]> error. Any idea what is wrong with the code?

```
verbruik_data = sess.post('https://mijn.greenchoice.nl/microbus/request', {
        'name': 'ProductkostenOphalenRequest',
        'message': {
            'productType': 3,
            'periodeType': 3,
            'jaar': 2021,
            'maand': 11,
            'dag': 1
        }
    }, headers={
        'accept': 'application/json, text/plain, */*',
        'content-type': 'application/json;charset=UTF-8',
        'referer': 'https://mijn.greenchoice.nl/verbruik',
        'host': 'mijn.greenchoice.nl',
        'origin': 'https://mijn.greenchoice.nl'
    })
    print(verbruik_data)

**Comment by DismissedGuy** [comment]
@DonJuape I haven't really looked into that endpoint myself yet, so unfortunately I'm not really sure what's wrong exactly. It's difficult to tell especially since the API is undocumented. Maybe you could look into the data that the API returns? e.g. print `verbruik_data.text` and see if that contains more info.

One thing I'm noticing though about your code is that it's needlessly complicated. From my tests so far, simply using `sess.post("<microbus_url>", json={"some": "data"})` should be enough for the API to return a proper reply. I can't imagine that being different from the microbus endpoint that you want to call, so you could try that just to rule out any errors in the headers that it might not like (since it's returning a server error code). You can take a look at [this](https://github.com/DismissedGuy/homeassistant-greenchoice/blob/master/custom_components/greenchoice/sensor.py#L255-L289) snippet from my integration to see how it's successfully calling the microbus endpoint.

**Comment by DismissedGuy** [comment]
@DonJuape Nevermind about my previous comment; I just restarted my HA container and am running into the exact same issue as you. The logging in does indeed still work fine; it appears that only microbus is broken. I will investigate a bit and see if I can find the issue, though I'm not sure if I'll be able to fix it today.

**Comment by DismissedGuy** [comment]
> @DonJuape Nevermind about my previous comment; I just restarted my HA container and am running into the exact same issue as you. The logging in does indeed still work fine; it appears that only microbus is broken. I will investigate a bit and see if I can find the issue, though I'm not sure if I'll be able to fix it today.

This issue actually appears to be on Greenchoice's end, as I can no longer access my meter data from the website either (https://mijn.greenchoice.nl/meterstanden-overzicht). I just tried calling `ProductkostenOphalenRequest` from microbus and I can still access that however, so there must be something wrong with your code to trigger that server error. One thing that I did find was that microbus would take a *long* time to reply if you misspelled the request name in the payload before actually returning a 500 status, so you might want to check that.

**Comment by tivoo** [comment]
Hi @DismissedGuy the energy consumption meters now seem to pick up data from the API, however the currentGas sensor does not seem to show up. Am I missing something here?
```

2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Retrieving meter values
2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Request: POST /microbus/request
2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Access cookie expired, triggering refresh
2022-02-03 10:13:18 INFO (SyncWorker_8) [custom_components.greenchoice.sensor] Retrieving login cookies
2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Purging existing session
2022-02-03 10:13:19 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Logging in with username and password
2022-02-03 10:13:19 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Signing in using OIDC
2022-02-03 10:13:20 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Login success
2022-02-03 10:13:20 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Request: POST /microbus/request
2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meterstanden (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_total (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_total (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
...
2022-02-03 10:15:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.meterstanden has unit None which is unsupported for device_class energy
```

**Comment by DismissedGuy** [comment]
> Hi @DismissedGuy the energy consumption meters now seem to pick up data from the API, however the currentGas sensor does not seem to show up. Am I missing something here?
> ```
> 
> 2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Retrieving meter values
> 2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Request: POST /microbus/request
> 2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Access cookie expired, triggering refresh
> 2022-02-03 10:13:18 INFO (SyncWorker_8) [custom_components.greenchoice.sensor] Retrieving login cookies
> 2022-02-03 10:13:18 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Purging existing session
> 2022-02-03 10:13:19 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Logging in with username and password
> 2022-02-03 10:13:19 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Signing in using OIDC
> 2022-02-03 10:13:20 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Login success
> 2022-02-03 10:13:20 DEBUG (SyncWorker_8) [custom_components.greenchoice.sensor] Request: POST /microbus/request
> 2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.meterstanden (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:22 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_consumption_total (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_high (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_low (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> 2022-02-03 10:13:24 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.energy_return_total (<class 'custom_components.greenchoice.sensor.GreenchoiceSensor'>) implements device_state_attributes. Please report it to the custom component author.
> ...
> 2022-02-03 10:15:10 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.meterstanden has unit None which is unsupported for device_class energy
> ```

That sounds about right - I haven't gotten around to implementing any other meters yet except for energy consumption / return. The other values are retrieved using different endpoints, and I haven't gotten around to inspecting those yet. Just out of curiosity - are the energy meters working for you properly?

I can't make any promises, but perhaps I can take a look at implementing some of the additional meters this weekend.

**Comment by rolandb5** [comment]
Hi @DismissedGuy , any plans to add pricing information from your contract to this addon? With the new energy dashboard, it would be supernice to dynamically extract the contract pricing information for gas, peak power and normal power. Like in this example:

<img width="989" alt="Screenshot 2022-11-13 at 09 42 40" src="https://user-images.githubusercontent.com/17737913/201513364-34e8e612-4fee-49f0-8ffd-af1064275342.png">

**Comment by DismissedGuy** [comment]
> Hi @DismissedGuy , any plans to add pricing information from your contract to this addon? With the new energy dashboard, it would be supernice to dynamically extract the contract pricing information for gas, peak power and normal power. Like in this example:
> 
> <img alt="Screenshot 2022-11-13 at 09 42 40" width="989" src="https://user-images.githubusercontent.com/17737913/201513364-34e8e612-4fee-49f0-8ffd-af1064275342.png">

Unfortunately I don't really have the time or motivation to work on this project anymore, since I no longer actively use home assistant. However, it looks like some people have forked my fork and expanded upon it, adding new features and refactoring the code:
- https://github.com/barisdemirdelen/homeassistant-greenchoice
- https://github.com/fvschie/homeassistant-greenchoice

Maybe one of them already supports retrieving the pricing information. If not, I think it might be better to open an issue on one of these repositories since they appear to be more actively maintained than mine.

**Comment by rolandb5** [comment]
Thanks for the hint. Sensors are added in: https://github.com/barisdemirdelen/homeassistant-greenchoice :-)

**Comment by DismissedGuy** [comment]
Great! :D
