### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by dennisstorm-hass** [jessevl/homeassistant-greenchoice#4]
I've installed the component and configured it. I was able to get my access token and contract ID via Postman. However, when running the platform I'm getting the following issue:

2020-05-07 13:39:39 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up greenchoice platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 55, in setup_platform
    greenchoice_api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/greenchoice/sensor.py", line 175, in update
    self.token = json_result["access_token"]
KeyError: 'access_token'

Looks like the platform can't get the access_token programmatically from the Greencoice API service anymore

**Comment by eelcohn** [comment]
I've experienced the same problem when using a password with complex/special characters like +, @, \ etc. and I've pushed an update to the repository which fixed this problem for me. Perhaps it will work for you as well.
