### ISSUE TITLE
Doesn't work if you don't have gas

### ISSUE THREAD

**Issue by sophof** [jessevl/homeassistant-greenchoice#7]
Just tried out the integration, but get an error during setup:

```
Error while setting up greenchoice platform for sensor
Traceback (most recent call last):
  File "/home/hass/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 184, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hass/.homeassistant/custom_components/greenchoice/sensor.py", line 56, in setup_platform
    greenchoice_api.update()
  File "/home/hass/.local/lib/python3.8/site-packages/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/home/hass/.homeassistant/custom_components/greenchoice/sensor.py", line 195, in update
    self.result["currentGas"] = json_result[1]["MeterstandenOutput"][0]["Hoog"]
IndexError: list index out of range
```

so it looks like it can't handle the result if there's no gas output.

**Comment by 4umedia** [comment]
Same problem here

**Comment by dutchcandy** [comment]
In my situation, gas is the third product, not the second. So in my situation,I believe json_result[2] shoudl be used for gas

**Comment by erwinvana** [comment]
Same issue and error, also no Gas only electricity

**Comment by ElwinMagnus** [comment]
Same problem here, is there a work around possible by changing or removing the product number in the  greenchoice/sensor.py file?

**Comment by jessevl** [comment]
Should be fixed now, can anyone confirm?

**Comment by ElwinMagnus** [comment]
Yes it works! thanks a lot.

**Comment by jessevl** [comment]
Great, thanks to @HumanPrinter #22
